Read Dataset(csv,json,parquet)

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import numpy as np

CSV file

In [4]:
csv_path1="D:\\fasith\\customers.csv.csv"

Read Datasets

In [5]:
import pandas as pd

In [6]:
df_csv1 = pd.read_csv(csv_path1)

In [7]:
df_csv1

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [8]:
df_csv1.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [9]:
csv_path2="D:\\fasith\\organizations.csv.csv"

In [10]:
csv_path3="D:\\fasith\\user_profile.csv.csv"

In [11]:
df_csv2 = pd.read_csv(csv_path2)
df_csv3 = pd.read_csv(csv_path3)

In [12]:
df_csv2

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,E84A904909dF528,Liu-Hoover,http://www.day-hartman.org/,Western Sahara,Ergonomic zero administration knowledge user,1980,Online Publishing,6852
1,2,AAC4f9aBF86EAeF,Orr-Armstrong,https://www.chapman.net/,Algeria,Ergonomic radical budgetary management,1970,Import / Export,7994
2,3,ad2eb3C8C24DB87,Gill-Lamb,http://lin.com/,Cote d'Ivoire,Programmable intermediate conglomeration,2005,Apparel / Fashion,5105
3,4,D76BB12E5eE165B,Bauer-Weiss,https://gillespie-stout.com/,United States of America,Synergistic maximized definition,2015,Dairy,9069
4,5,2F31EddF2Db9aAE,Love-Palmer,https://kramer.com/,Denmark,Optimized optimizing moderator,2010,Management Consulting,6991
...,...,...,...,...,...,...,...,...,...
995,996,e5CEc38aa9A580b,Bullock Group,https://medina-bernard.com/,Turkmenistan,Public-key scalable conglomeration,1998,Wine / Spirits,6547
996,997,cEF9B4675E4bBd0,Mason Inc,https://franco-walls.com/,United States of America,Distributed exuding initiative,2015,Law Enforcement,9723
997,998,9abEb8aaFd25E04,Houston and Sons,http://mcgee.com/,Kenya,Stand-alone multi-state neural-net,1981,Civic / Social Organization,5355
998,999,de5Fc71DE825bFc,Olson-Solomon,https://koch.com/,Cocos (Keeling) Islands,Virtual responsive moderator,2013,Investment Banking / Venture,3825
999,1000,3ddb89ecD83B533,"Maddox, Owen and Shepherd",https://www.hamilton.com/,Guinea,Reactive bottom-line pricing structure,2019,Animation,4467

In [13]:
df_csv3

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,8717bbf45cCDbEe,Shelia,Mahoney,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer
1,2,3d5AD30A4cD38ed,Jo,Rivers,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer
2,3,810Ce0F276Badec,Sheryl,Lowery,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy
3,4,BF2a889C00f0cE1,Whitney,Hooper,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist
4,5,9afFEafAe1CBBB9,Lindsey,Rice,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer
...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer
996,997,ECddaFEDdEc4FAB,Donna,Barry,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator
997,998,2adde51d8B8979E,Cathy,Mckinney,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor
998,999,Fb2FE369D1E171A,Jermaine,Phelps,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person
999,1000,8b756f6231DDC6e,Lee,Tran,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability"

JSON files

In [14]:
import json

In [15]:
import pandas as pd

In [16]:
json_path1="D:\\fasith\\employees.json.json"

Read Datasets

In [17]:
with open(json_path1, "r") as f:
    raw_data1 = json.load(f)

In [18]:
df_json1 = pd.json_normalize(raw_data1)

In [19]:
df_json1

,employee.id,employee.name,employee.position,employee.department.id,employee.department.name,employee.department.manager.id,employee.department.manager.name,employee.department.manager.contact.email,employee.department.manager.contact.phone,employee.projects
0,E00001,Traci Kelly,"Geologist, wellsite",D006,Monetize,M1179,Alicia Hughes,patricia05@example.net,2735306585,"[{'projectId': 'P3213', 'projectName': 'Functi..."
1,E00002,Thomas Mendoza,Magazine journalist,D085,Harness,M6539,Bryan Jones,leeeric@example.net,(461)803-4754x44615,"[{'projectId': 'P6704', 'projectName': 'Expand..."
2,E00003,Natasha Williams,Tourism officer,D083,Harness,M7225,Stacey Johnston,williamcunningham@example.net,(374)225-2216x990,"[{'projectId': 'P4328', 'projectName': 'Synerg..."
3,E00004,Walter Hanna,Herpetologist,D076,Expedite,M5714,Mark Acosta,zfletcher@example.com,(698)802-9911,"[{'projectId': 'P1496', 'projectName': 'Polari..."
4,E00005,Daniel Williams,Social researcher,D049,Cultivate,M2305,Misty Cummings,erin74@example.net,001-713-617-8609x1921,"[{'projectId': 'P3965', 'projectName': 'Pre-em..."
...,...,...,...,...,...,...,...,...,...,...
561,E00562,Bryan Davis,Volunteer coordinator,D071,Exploit,M7771,Dana Carey,kathryngillespie@example.com,(938)301-8221x21874,"[{'projectId': 'P3934', 'projectName': 'Persis..."
562,E00563,Jennifer Wiggins,Financial controller,D021,Exploit,M6800,Amber Robles,ashley05@example.com,+1-387-792-0869x56271,"[{'projectId': 'P8423', 'projectName': 'Down-s..."
563,E00564,Michael Williamson,Purchasing manager,D026,Monetize,M9412,Nancy Sanchez,adamsmisty@example.net,5078648662,"[{'projectId': 'P1329', 'projectName': 'Multi-..."
564,E00565,Sharon Chan,"Teacher, adult education",D011,Drive,M3824,Eric Adams,carol69@example.org,764.873.8334,"[{'projectId': 'P3881', 'projectName': 'Extend..."
565,E00566,James Roberts,"Accountant, chartered management",D004,Monetize,M4049,Russell Wilson,barnettdavid@example.net,892.832.7680,"[{'projectId': 'P6396', 'projectName': 'Fully-..."

In [21]:
json_path2="D:\\fasith\\products.json.json"

In [22]:
with open(json_path2, "r") as f:
    data2 = json.load(f)

In [23]:
df_json2 = pd.json_normalize(data2)

In [24]:
df_json2

,productId,productName,description,brand,category,price,currency,images,variants,reviews,stock.available,stock.quantity,dimensions.weight,dimensions.width,dimensions.height,dimensions.depth,ratings.averageRating,ratings.numberOfReviews
0,1001,Wireless Headphones,Noise-cancelling wireless headphones with Blue...,SoundPro,Electronics,199.99,USD,"[https://example.com/products/1001/main.jpg, h...","[{'variantId': '1001_01', 'color': 'Black', 'p...","[{'reviewId': 501, 'userId': 101, 'username': ...",True,50,0.5kg,18cm,20cm,8cm,4.7,120
1,1002,Smartphone Case,"Durable and shockproof case for smartphones, a...",CaseMate,Accessories,29.99,USD,"[https://example.com/products/1002/main.jpg, h...","[{'variantId': '1002_01', 'color': 'Black', 'p...","[{'reviewId': 601, 'userId': 103, 'username': ...",True,200,0.2kg,8cm,15cm,1cm,4.4,80
2,1003,4K Ultra HD Smart TV,55-inch 4K Ultra HD Smart TV with built-in Wi-...,Visionary,Electronics,799.99,USD,"[https://example.com/products/1003/main.jpg, h...","[{'variantId': '1003_01', 'screenSize': '55 in...","[{'reviewId': 701, 'userId': 105, 'username': ...",True,30,15kg,123cm,80cm,10cm,4.8,250
3,1004,Bluetooth Speaker,Portable Bluetooth speaker with 12-hour batter...,AudioX,Electronics,59.99,USD,"[https://example.com/products/1004/main.jpg, h...","[{'variantId': '1004_01', 'color': 'Red', 'pri...","[{'reviewId': 801, 'userId': 107, 'username': ...",True,100,0.3kg,15cm,8cm,5cm,4.6,150
4,1005,Winter Jacket,Men's water-resistant winter jacket with a fur...,ColdTech,Clothing,129.99,USD,"[https://example.com/products/1005/main.jpg, h...","[{'variantId': '1005_01', 'size': 'M', 'color'...","[{'reviewId': 901, 'userId': 109, 'username': ...",True,80,1.5kg,60cm,85cm,5cm,4.5,60

In [25]:
json_path3="D:\\fasith\\user_profiles.json.json"

In [26]:
with open(json_path3, "r") as f:
    data3 = json.load(f)

In [27]:
df_json3 = pd.json_normalize(data3)

In [28]:
df_json3

,userId,username,email,passwordHash,activityLogs,profile.firstName,profile.lastName,profile.birthDate,profile.gender,profile.avatarUrl,...,preferences.language,preferences.theme,preferences.notifications.email,preferences.notifications.sms,preferences.notifications.push,preferences.privacy.showOnlineStatus,preferences.privacy.profileVisibility,accountStatus.isActive,accountStatus.lastLogin,accountStatus.createdAt
0,1,johndoe,johndoe@example.com,abc123hashedpassword,"[{'timestamp': '2025-01-09T14:20:00Z', 'activi...",John,Doe,1990-01-01,male,https://example.com/avatars/johndoe.jpg,...,en,dark,True,False,True,False,friends,True,2025-01-10T12:45:00Z,2022-05-15T08:30:00Z
1,2,janedoe,janedoe@example.com,xyz987hashedpassword,"[{'timestamp': '2025-01-09T18:30:00Z', 'activi...",Jane,Doe,1992-04-12,female,https://example.com/avatars/janedoe.jpg,...,fr,light,False,True,True,True,public,True,2025-01-10T09:15:00Z,2023-03-20T11:00:00Z

Parquet File

In [29]:
pip install pyarrow

Requirement already satisfied: pyarrow in C:\Users\Jayabharath\anaconda\envs\dataengg\Lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd

In [31]:
parquet_path1="D:\\fasith\\house-price.parquet"

In [32]:
df_parquet= pd.read_parquet(parquet_path1, engine="pyarrow")

In [33]:
df_parquet

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [50]:
df_parquet1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
parquet_path3="D:\\fasith\\weather.parquet"

In [52]:
df_parquet2 = pd.read_parquet(parquet_path3, engine="pyarrow")

In [53]:
df_parquet2

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30,SW,NW,6,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39,E,W,4,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85,N,NNE,6,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54,WNW,W,30,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50,SSE,ESE,20,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76,SSE,NW,7,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48,NNW,NNW,2,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43,ENE,ENE,11,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46,SSW,WNW,6,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78,NW,WNW,31,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No